wandb_version: 1

ENV_NAME:
  desc: null
  value: backgammon
LR:
  desc: null
  value: 0.00025
NUM_ENVS:
  desc: null
  value: 64
NUM_STEPS:
  desc: null
  value: 256
TOTAL_TIMESTEPS:
  desc: null
  value: 5000000
UPDATE_EPOCHS:
  desc: null
  value: 30
NUM_MINIBATCHES:
  desc: null
  value: 8
GAMMA:
  desc: null
  value: 0.99
GAE_LAMBDA:
  desc: null
  value: 0.95
CLIP_EPS:
  desc: null
  value: 0.2
ENT_COEF:
  desc: null
  value: 0.01
VF_COEF:
  desc: null
  value: 0.5
MAX_GRAD_NORM:
  desc: null
  value: 0.5
ACTIVATION:
  desc: null
  value: tanh
NUM_UPDATES:
  desc: null
  value: 10000
MINIBATCH_SIZE:
  desc: null
  value: 32
ANNEAL_LR:
  desc: null
  value: true
VS_RANDOM:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.15.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684809100.943778
    t:
      1:
      - 12
      - 45
      - 55
      2:
      - 12
      - 45
      - 55
      3:
      - 16
      - 23
      4: 3.10.0
      5: 0.15.2
      8:
      - 5
