name: pypi

on: [push]

jobs:
  build-n-publish:
    name: pypi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: install
      run: >-
        python -m
        pip install
        build
        --user
    - name: build
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: publish
      if: github.event_name == 'release' && github.event.action == 'published'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
